#!/bin/bash

export AGENT_HOME=$HOME/test_agent
export PACKAGING=packaging
export TAR_NAME=javaagent
export VERSION=1.0

rm -rf $AGENT_HOME/$TAR_NAME-$VERSION/*
tar -xvf $PACKAGING/target/$TAR_NAME-$VERSION.tar -C $AGENT_HOME > /dev/null


