/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agent_jvmti_JvmtiUtils */

#ifndef _Included_agent_jvmti_JvmtiUtils
#define _Included_agent_jvmti_JvmtiUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agent_jvmti_JvmtiUtils
 * Method:    findObjectsByClassHelper
 * Signature: (Ljava/lang/Class;I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_agent_jvmti_JvmtiUtils_findObjectsByClassHelper
  (JNIEnv *, jobject, jclass, jint);

/*
 * Class:     agent_jvmti_JvmtiUtils
 * Method:    getLoadedClasses
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_agent_jvmti_JvmtiUtils_getLoadedClasses
  (JNIEnv *, jobject);

/*
 * Class:     agent_jvmti_JvmtiUtils
 * Method:    changeCredential
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_agent_jvmti_JvmtiUtils_changeCredential
  (JNIEnv *, jobject, jint);

/*
 * Class:     agent_jvmti_JvmtiUtils
 * Method:    resetCredential
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_agent_jvmti_JvmtiUtils_resetCredential
  (JNIEnv *, jobject);

/*
 * Class:     agent_jvmti_JvmtiUtils
 * Method:    getProcId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_agent_jvmti_JvmtiUtils_getProcId
  (JNIEnv *, jobject);

/*
 * Class:     agent_jvmti_JvmtiUtils
 * Method:    attachJvm
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_agent_jvmti_JvmtiUtils_attachJvm
  (JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
