/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agent_jvmti_JvmtiUtils */

#ifndef _Included_agent_jvmti_JvmtiUtils
#define _Included_agent_jvmti_JvmtiUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agent_jvmti_JvmtiUtils
 * Method:    findObjectsByClassHelper
 * Signature: (Ljava/lang/Class;I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_agent_jvmti_JvmtiUtils_findObjectsByClassHelper
  (JNIEnv *, jobject, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
