#!/bin/bash

CLASS=Test
CWD=$(pwd)
CR_CWD=/usr/src
BUILD_DIR=build
CR_BUILD_DIR=$CR_CWD/$BUILD_DIR

mkdir -p $BUILD_DIR
$JAVA_HOME/bin/javac -d $BUILD_DIR $CLASS.java

docker run --rm \
		   --name javaApp \
		   -w $CR_CWD \
		   -v "$JAVA_HOME":$JAVA_HOME \
		   -v "$CWD/$BUILD_DIR":$CR_BUILD_DIR \
		   ubuntu $JAVA_HOME/bin/java -cp $CR_BUILD_DIR $CLASS

rm -rf $BUILD_DIR