#!/bin/bash

if [ "$1" = "-i" ]
then
    export main_class=agent.builtin.tools.CostTimeByInvoke
    shift
else
    export main_class=agent.builtin.tools.CostTimeByCallChain
fi

$(dirname "$0")/run $*
