#!/bin/bash

export type=server
source $(dirname $0)/../../common/bin/env

export plugin_dir=$base_dir/lib/plugin
export classpath=$common_lib_base_dir/*:$common_lib_core_dir/*:$common_lib_delegate_dir/*:$plugin_dir/*

$JAVA_HOME/bin/java -cp $classpath $main_class $conf_file $*
